name: Run Ansible Playbook

on:
  push:
    paths:
      - 'Ansible/playbook-linux.yml'

jobs:
  run-playbook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Run Ansible Playbook
        run: |
          ansible-playbook Ansible/playbook-linux.yml -i Ansible/hosts
          Ansible/playbook-windows.yml -i Ansible/hosts
